name: Build, test, package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  cxx-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-cxx.yml@v5.4.0

  python-build-workflow:
    uses: InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/.github/workflows/build-test-package-python.yml@v5.4.0
    secrets:
      pypi_password: ${{ secrets.pypi_password }}
    with:
      manylinux-platforms: '["_2_28-x64", "_2_28-aarch64"]'
      python3-minor-versions: '["9", "10", "11"]'
